INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, ROLE, COUNTRY, PHONE_NUMBER) VALUES ('TOMAS', 'MORKUNAS', 'TOMASMO@GMAIL.COM', 'NAMU ADRESAS', 'ADMIN', 'LIETUVA', '+37068443391');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, ROLE, COUNTRY, PHONE_NUMBER) VALUES ('DOMAS', 'NORKUNAS', 'DOMASMO@GMAIL.COM', 'NAMU ADRESAS', 'USER', 'LIETUVA', '+37068443392');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, ROLE, COUNTRY, PHONE_NUMBER) VALUES ('ROMAS', 'TORKUNAS', 'ROMASMO@GMAIL.COM', 'NAMU ADRESAS', 'USER', 'LIETUVA', '+37068443392');

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE, PRODUCT_AVAILABILITY) VALUES ('Product1','10','10','1');
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE, PRODUCT_AVAILABILITY) VALUES ('Product2','20','20','1');
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_QUANTITY, PRODUCT_PRICE, PRODUCT_AVAILABILITY) VALUES ('Product3','30','30','1');

